# TODO : Add support for Metastore DB Integration

# Use AWS Glue image as the base
FROM amazon/aws-glue-libs:glue_libs_4.0.0_image_01

# https://stackoverflow.com/a/74598849
RUN rm /home/glue_user/spark/conf/hive-site.xml

# Switch to root user to install necessary dependencies
USER root

# Upgrade pip to the latest version
RUN pip3 install --upgrade pip

# Install Poetry for dependency management
RUN pip3 install poetry


# Add Kafka JAR for structured streaming
ADD https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.3.0/spark-sql-kafka-0-10_2.12-3.3.0.jar /opt/spark/jars/
ADD https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/2.8.0/kafka-clients-2.8.0.jar /opt/spark/jars/

# Add Iceberg JARs for Iceberg integration
ADD https://repo1.maven.org/maven2/org/apache/iceberg/iceberg-spark-runtime-3.3_2.12/0.14.0/iceberg-spark-runtime-3.3_2.12-0.14.0.jar /opt/spark/jars/
ADD https://repo1.maven.org/maven2/org/apache/iceberg/iceberg-api/0.14.0/iceberg-api-0.14.0.jar /opt/spark/jars/
ADD https://repo1.maven.org/maven2/org/apache/iceberg/iceberg-core/0.14.0/iceberg-core-0.14.0.jar /opt/spark/jars/


WORKDIR /app
COPY pyproject.toml poetry.lock* /app/

# Install project dependencies via poetry
RUN poetry install

COPY src /app/src


# Run the PySpark job
ENTRYPOINT [ "/bin/bash", "-l", "-c" ]
CMD ["/bin/bash"]

